apiVersion: v1
kind: Service
metadata:
  name: gestion-tickets-it-service
spec:
  type: LoadBalancer
  selector:
    app: gestion-tickets-it
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
